version: '3'
services:
  # Quasar-App-Container
  quasar-app:
    build:
      context: .
      dockerfile: Dockerfile # Dateiname des Dockerfiles, falls nicht im Standard "Dockerfile" genannt
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    ports:
      - 80:80

